import { MerchantOrder, PartnerMenuItem, CouponItem, PartnerProfile, NotificationItem } from '../types';

export const INITIAL_ORDERS: MerchantOrder[] = [
  {
    orderId: 'MS-9021',
    customerName: 'Rajesh Kumar',
    deliveryType: 'priorityDelivery',
    items: [
      { name: 'Paneer Butter Masala', quantity: 2, price: 480 },
      { name: 'Garlic Naan', quantity: 4, price: 160 },
      { name: 'Dal Makhani (Half)', quantity: 1, price: 180 },
    ],
    waitTime: '08:45',
    status: 'incoming',
    statusRaw: 'PENDING_MERCHANT_CONFIRMATION',
  },
  {
    orderId: 'MS-9025',
    customerName: 'Ananya Singh',
    deliveryType: 'selfPickup',
    items: [
      { name: 'Veg Biryani (Large)', quantity: 1, price: 220 },
      { name: 'Raita (Extra)', quantity: 1, price: 40 },
    ],
    waitTime: '03:12',
    status: 'incoming',
    statusRaw: 'PENDING_MERCHANT_CONFIRMATION',
  },
  {
    orderId: 'MS-9018',
    customerName: 'Priya Sharma',
    deliveryType: 'delivery',
    items: [
      { name: 'Butter Chicken', quantity: 1, price: 320 },
      { name: 'Tandoori Roti', quantity: 6, price: 120 },
      { name: 'Gulab Jamun', quantity: 2, price: 80 },
    ],
    waitTime: '12:30',
    status: 'incoming',
    statusRaw: 'PENDING_MERCHANT_CONFIRMATION',
  },
  {
    orderId: 'MS-9015',
    customerName: 'Amit Verma',
    deliveryType: 'priorityDelivery',
    items: [
      { name: 'Chole Bhature', quantity: 2, price: 260 },
      { name: 'Lassi (Sweet)', quantity: 2, price: 100 },
    ],
    waitTime: '05:20',
    status: 'preparing',
    statusRaw: 'ACCEPTED_BY_MERCHANT',
  },
  {
    orderId: 'MS-9013',
    customerName: 'Sneha Patel',
    deliveryType: 'selfPickup',
    items: [
      { name: 'Masala Dosa', quantity: 3, price: 270 },
      { name: 'Sambhar', quantity: 3, price: 90 },
    ],
    waitTime: '18:40',
    status: 'preparing',
    statusRaw: 'PREPARING',
  },
  {
    orderId: 'MS-9012',
    customerName: 'Vikram Joshi',
    deliveryType: 'delivery',
    items: [
      { name: 'Paneer Tikka', quantity: 1, price: 280 },
      { name: 'Butter Naan', quantity: 4, price: 160 },
      { name: 'Mango Lassi', quantity: 2, price: 120 },
    ],
    waitTime: '15:55',
    status: 'preparing',
    statusRaw: 'PREPARING',
  },
  {
    orderId: 'MS-9005',
    customerName: 'Karan Malhotra',
    deliveryType: 'delivery',
    items: [
      { name: 'Chicken Biryani', quantity: 2, price: 520 },
      { name: 'Raita', quantity: 2, price: 60 },
    ],
    waitTime: '30:00',
    status: 'ready',
    statusRaw: 'READY_FOR_PICKUP',
    pickupOtp: '4829',
    driverName: 'Rahul Verma',
    driverPhone: '+91 98765 43210',
    driverStatus: 'DRIVER_ARRIVED_AT_MERCHANT',
  },
  {
    orderId: 'MS-9003',
    customerName: 'Deepa Reddy',
    deliveryType: 'priorityDelivery',
    items: [
      { name: 'Thali (Special)', quantity: 1, price: 350 },
    ],
    waitTime: '35:15',
    status: 'ready',
    statusRaw: 'READY_FOR_PICKUP',
    pickupOtp: '9102',
    driverName: 'Sanjay Yadav',
    driverPhone: '+91 94567 11223',
    driverStatus: 'DRIVER_ASSIGNED',
  },
  {
    orderId: 'MS-8998',
    customerName: 'Rohan Mehra',
    deliveryType: 'delivery',
    items: [
      { name: 'Kadai Paneer', quantity: 1, price: 290 },
      { name: 'Jeera Rice', quantity: 1, price: 140 },
    ],
    waitTime: '40:00',
    status: 'outForDelivery',
    statusRaw: 'OUT_FOR_DELIVERY',
    pickupOtp: '7721',
    driverName: 'Manoj Kumar',
    driverPhone: '+91 91234 56789',
    driverStatus: 'EN_ROUTE_TO_CUSTOMER',
  },
  {
    orderId: 'MS-8970',
    customerName: 'Sunita Mishra',
    deliveryType: 'delivery',
    items: [
      { name: 'Shahi Paneer', quantity: 1, price: 310 },
      { name: 'Butter Naan', quantity: 2, price: 80 },
    ],
    waitTime: '00:00',
    status: 'delivered',
    statusRaw: 'DELIVERED',
  },
  {
    orderId: 'MS-8965',
    customerName: 'Alok Gupta',
    deliveryType: 'delivery',
    items: [
      { name: 'Veg Manchurian', quantity: 1, price: 210 },
      { name: 'Fried Rice', quantity: 1, price: 180 },
    ],
    waitTime: '00:00',
    status: 'cancelled',
    statusRaw: 'CANCELLED_BY_CUSTOMER',
    refundStatus: 'Processed to UPI (₹390)',
  },
];

export const INITIAL_MENU: PartnerMenuItem[] = [
  {
    id: 'item-1',
    name: 'Paneer Butter Masala',
    category: 'Main Course',
    price: 240,
    prepTimeMinutes: 20,
    isVeg: true,
    isBestseller: true,
    status: 'Available',
    description: 'Rich tomato & cashew gravy cooked with tender cottage cheese cubes and fresh butter.',
    imageUrl: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=400&q=80',
  },
  {
    id: 'item-2',
    name: 'Dal Makhani',
    category: 'Main Course',
    price: 180,
    prepTimeMinutes: 15,
    isVeg: true,
    isBestseller: true,
    status: 'Available',
    description: 'Slow-simmered whole black lentils, red kidney beans, butter and cream.',
    imageUrl: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=400&q=80',
  },
  {
    id: 'item-3',
    name: 'Veg Dum Biryani',
    category: 'Biryani',
    price: 220,
    prepTimeMinutes: 25,
    isVeg: true,
    isBestseller: true,
    status: 'Available',
    description: 'Fragrant basmati rice layered with spiced vegetables, saffron, and aromatic herbs.',
    imageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=400&q=80',
  },
  {
    id: 'item-4',
    name: 'Garlic Naan',
    category: 'Bread',
    price: 40,
    prepTimeMinutes: 10,
    isVeg: true,
    isBestseller: false,
    status: 'Available',
    description: 'Crisp oven-baked flatbread infused with roasted garlic and coriander butter.',
  },
  {
    id: 'item-5',
    name: 'Chole Bhature (2 Pcs)',
    category: 'Main Course',
    price: 130,
    prepTimeMinutes: 15,
    isVeg: true,
    isBestseller: true,
    status: 'Available',
    description: 'Spiced Punjabi chickpea curry served with hot puffed deep-fried bhaturas and pickles.',
    imageUrl: 'https://images.unsplash.com/photo-1626132647523-66f5bf380027?auto=format&fit=crop&w=400&q=80',
  },
  {
    id: 'item-6',
    name: 'Masala Dosa',
    category: 'South Indian',
    price: 90,
    prepTimeMinutes: 15,
    isVeg: true,
    isBestseller: false,
    status: 'Available',
    description: 'Crispy golden crepe stuffed with mildly spiced potato filling, coconut chutney & sambar.',
  },
  {
    id: 'item-7',
    name: 'Butter Chicken',
    category: 'Main Course',
    price: 320,
    prepTimeMinutes: 25,
    isVeg: false,
    isBestseller: true,
    status: 'Available',
    description: 'Tender chicken pieces simmered in silky tomato butter sauce with fenugreek.',
    imageUrl: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=400&q=80',
  },
  {
    id: 'item-8',
    name: 'Gulab Jamun (2 Pcs)',
    category: 'Dessert',
    price: 40,
    prepTimeMinutes: 5,
    isVeg: true,
    isBestseller: false,
    status: 'Available',
    description: 'Soft fried milk dumplings soaked in cardamom flavored rose water syrup.',
  },
  {
    id: 'item-9',
    name: 'Mango Lassi',
    category: 'Beverages',
    price: 60,
    prepTimeMinutes: 5,
    isVeg: true,
    isBestseller: true,
    status: 'Available',
    description: 'Thick creamy churned yogurt blended with sweet mango pulp.',
  },
];

export const INITIAL_COUPONS: CouponItem[] = [
  {
    id: 'c-1',
    code: 'WELCOME50',
    title: '50% Off First 3 Orders',
    subtitle: 'Flat ₹50 discount on orders above ₹199',
    discount: 50,
    visibility: 'public',
    status: 'Active',
  },
  {
    id: 'c-2',
    code: 'SHARDA100',
    title: 'Grand Kitchen Special',
    subtitle: 'Flat ₹100 off on family meals above ₹499',
    discount: 100,
    visibility: 'public',
    status: 'Active',
  },
  {
    id: 'c-3',
    code: 'VIPPARTNER',
    title: 'Exclusive Member Perk',
    subtitle: 'Secret discount code for loyalty repeat customers',
    discount: 75,
    visibility: 'private',
    status: 'Active',
  },
];

export const INITIAL_PROFILE: PartnerProfile = {
  id: 'REST-7890',
  name: 'Maa Sharda Grand Kitchen',
  phone: '+91 98765 43210',
  address: 'Shop 14, Commercial Arcade, Hazratganj, Lucknow, UP 226001',
  owner_name: 'Sumit Kumar',
  owner_email: 'sumit.maasharda@gmail.com',
  image_url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=400&q=80',
  cover_url: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80',
  status: 'Active',
  delivery_minutes: 25,
  is_pure_veg: false,
  approval_status: 'approved',
};

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'n-1',
    title: 'New Order Received (#MS-9021)',
    message: 'Rajesh Kumar placed a priority order for ₹820. Please accept or reject within 5 minutes.',
    read: false,
    timestamp: '2 mins ago',
  },
  {
    id: 'n-2',
    title: 'Driver Arrived at Kitchen',
    message: 'Rahul Verma has arrived to pick up ready order #MS-9005.',
    read: false,
    timestamp: '14 mins ago',
  },
  {
    id: 'n-3',
    title: 'Order Delivered (#MS-8970)',
    message: 'Order #MS-8970 successfully handed over to customer. Payment credited to partner balance.',
    read: true,
    timestamp: '1 hour ago',
  },
  {
    id: 'n-4',
    title: 'Store Settings Updated',
    message: 'Your average kitchen preparation time was saved as 25 minutes.',
    read: true,
    timestamp: '3 hours ago',
  },
];
